# TCL File Generated by Component Editor 18.1
# Fri Jul 11 13:34:46 ICT 2025
# DO NOT MODIFY


# 
# active_ascon "active_ascon" v1.0
#  2025.07.11.13:34:46
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module active_ascon
# 
set_module_property DESCRIPTION ""
set_module_property NAME active_ascon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME active_ascon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL active_ascon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file RiSiEdgeDetector.sv SYSTEM_VERILOG PATH RTL/COMMON/RiSiEdgeDetector.sv
add_fileset_file config.sv SYSTEM_VERILOG PATH RTL/COMMON/config.sv
add_fileset_file ascon_core.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/ascon_core.sv
add_fileset_file compare.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/compare.sv
add_fileset_file counter.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/counter.sv
add_fileset_file flag.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/flag.sv
add_fileset_file fsm_control.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/fsm_control.sv
add_fileset_file function.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/function.sv
add_fileset_file get_ad_text.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_ad_text.sv
add_fileset_file get_config.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_config.sv
add_fileset_file get_data.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_data.sv
add_fileset_file get_key_nonce.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_key_nonce.sv
add_fileset_file get_tag.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_tag.sv
add_fileset_file handle_data.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/handle_data.sv
add_fileset_file permutation.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/permutation.sv
add_fileset_file sc_fifo.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/sc_fifo.sv
add_fileset_file store_data.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/store_data.sv
add_fileset_file update_state.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/update_state.sv
add_fileset_file pll_clk_0002.v VERILOG PATH RTL/DMAC/pll_clk/pll_clk_0002.v
add_fileset_file DMA_Core.sv SYSTEM_VERILOG PATH RTL/DMAC/DMA_Core.sv
add_fileset_file bdi_fifo.v VERILOG PATH RTL/DMAC/bdi_fifo.v
add_fileset_file ckn_ad_fifo.v VERILOG PATH RTL/DMAC/ckn_ad_fifo.v
add_fileset_file clk_divider.sv SYSTEM_VERILOG PATH RTL/DMAC/clk_divider.sv
add_fileset_file control_register_file.sv SYSTEM_VERILOG PATH RTL/DMAC/control_register_file.sv
add_fileset_file control_unit.sv SYSTEM_VERILOG PATH RTL/DMAC/control_unit.sv
add_fileset_file dma_to_sub.sv SYSTEM_VERILOG PATH RTL/DMAC/dma_to_sub.sv
add_fileset_file dynamic_config.sv SYSTEM_VERILOG PATH RTL/DMAC/dynamic_config.sv
add_fileset_file format_data.sv SYSTEM_VERILOG PATH RTL/DMAC/format_data.sv
add_fileset_file host_register.sv SYSTEM_VERILOG PATH RTL/DMAC/host_register.sv
add_fileset_file key_fifo.v VERILOG PATH RTL/DMAC/key_fifo.v
add_fileset_file pll_clk.v VERILOG PATH RTL/DMAC/pll_clk.v
add_fileset_file pulse_synchronizer.sv SYSTEM_VERILOG PATH RTL/DMAC/pulse_synchronizer.sv
add_fileset_file rd_request.sv SYSTEM_VERILOG PATH RTL/DMAC/rd_request.sv
add_fileset_file res_req_fifo.v VERILOG PATH RTL/DMAC/res_req_fifo.v
add_fileset_file rstn_synchronizer.sv SYSTEM_VERILOG PATH RTL/DMAC/rstn_synchronizer.sv
add_fileset_file store_ckn_ad.sv SYSTEM_VERILOG PATH RTL/DMAC/store_ckn_ad.sv
add_fileset_file sub_to_dma.sv SYSTEM_VERILOG PATH RTL/DMAC/sub_to_dma.sv
add_fileset_file tag_fifo.v VERILOG PATH RTL/DMAC/tag_fifo.v
add_fileset_file text_fifo.v VERILOG PATH RTL/DMAC/text_fifo.v
add_fileset_file wr_handle.sv SYSTEM_VERILOG PATH RTL/DMAC/wr_handle.sv
add_fileset_file wr_info_fifo.v VERILOG PATH RTL/DMAC/wr_info_fifo.v
add_fileset_file wr_request.sv SYSTEM_VERILOG PATH RTL/DMAC/wr_request.sv
add_fileset_file ascon_top.sv SYSTEM_VERILOG PATH RTL/ASCON_CASE/ascon_top.sv
add_fileset_file ascon_top3.sv SYSTEM_VERILOG PATH RTL/ASCON_CASE/ascon_top3.sv
add_fileset_file ascon_top4.sv SYSTEM_VERILOG PATH RTL/ASCON_CASE/ascon_top4.sv
add_fileset_file instance_fifo.v VERILOG PATH RTL/ASCON_CASE/instance_fifo.v
add_fileset_file active_ascon.sv SYSTEM_VERILOG PATH RTL/TOP_LEVEL/active_ascon.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL active_ascon
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file RiSiEdgeDetector.sv SYSTEM_VERILOG PATH RTL/COMMON/RiSiEdgeDetector.sv
add_fileset_file config.sv SYSTEM_VERILOG PATH RTL/COMMON/config.sv
add_fileset_file ascon_core.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/ascon_core.sv
add_fileset_file compare.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/compare.sv
add_fileset_file counter.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/counter.sv
add_fileset_file flag.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/flag.sv
add_fileset_file fsm_control.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/fsm_control.sv
add_fileset_file function.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/function.sv
add_fileset_file get_ad_text.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_ad_text.sv
add_fileset_file get_config.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_config.sv
add_fileset_file get_data.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_data.sv
add_fileset_file get_key_nonce.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_key_nonce.sv
add_fileset_file get_tag.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/get_tag.sv
add_fileset_file handle_data.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/handle_data.sv
add_fileset_file permutation.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/permutation.sv
add_fileset_file sc_fifo.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/sc_fifo.sv
add_fileset_file store_data.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/store_data.sv
add_fileset_file update_state.sv SYSTEM_VERILOG PATH RTL/ASCON_CORE/update_state.sv
add_fileset_file pll_clk_0002.v VERILOG PATH RTL/DMAC/pll_clk/pll_clk_0002.v
add_fileset_file DMA_Core.sv SYSTEM_VERILOG PATH RTL/DMAC/DMA_Core.sv
add_fileset_file bdi_fifo.v VERILOG PATH RTL/DMAC/bdi_fifo.v
add_fileset_file ckn_ad_fifo.v VERILOG PATH RTL/DMAC/ckn_ad_fifo.v
add_fileset_file clk_divider.sv SYSTEM_VERILOG PATH RTL/DMAC/clk_divider.sv
add_fileset_file control_register_file.sv SYSTEM_VERILOG PATH RTL/DMAC/control_register_file.sv
add_fileset_file control_unit.sv SYSTEM_VERILOG PATH RTL/DMAC/control_unit.sv
add_fileset_file dma_to_sub.sv SYSTEM_VERILOG PATH RTL/DMAC/dma_to_sub.sv
add_fileset_file dynamic_config.sv SYSTEM_VERILOG PATH RTL/DMAC/dynamic_config.sv
add_fileset_file format_data.sv SYSTEM_VERILOG PATH RTL/DMAC/format_data.sv
add_fileset_file host_register.sv SYSTEM_VERILOG PATH RTL/DMAC/host_register.sv
add_fileset_file key_fifo.v VERILOG PATH RTL/DMAC/key_fifo.v
add_fileset_file pll_clk.v VERILOG PATH RTL/DMAC/pll_clk.v
add_fileset_file pulse_synchronizer.sv SYSTEM_VERILOG PATH RTL/DMAC/pulse_synchronizer.sv
add_fileset_file rd_request.sv SYSTEM_VERILOG PATH RTL/DMAC/rd_request.sv
add_fileset_file res_req_fifo.v VERILOG PATH RTL/DMAC/res_req_fifo.v
add_fileset_file rstn_synchronizer.sv SYSTEM_VERILOG PATH RTL/DMAC/rstn_synchronizer.sv
add_fileset_file store_ckn_ad.sv SYSTEM_VERILOG PATH RTL/DMAC/store_ckn_ad.sv
add_fileset_file sub_to_dma.sv SYSTEM_VERILOG PATH RTL/DMAC/sub_to_dma.sv
add_fileset_file tag_fifo.v VERILOG PATH RTL/DMAC/tag_fifo.v
add_fileset_file text_fifo.v VERILOG PATH RTL/DMAC/text_fifo.v
add_fileset_file wr_handle.sv SYSTEM_VERILOG PATH RTL/DMAC/wr_handle.sv
add_fileset_file wr_info_fifo.v VERILOG PATH RTL/DMAC/wr_info_fifo.v
add_fileset_file wr_request.sv SYSTEM_VERILOG PATH RTL/DMAC/wr_request.sv
add_fileset_file ascon_top.sv SYSTEM_VERILOG PATH RTL/ASCON_CASE/ascon_top.sv
add_fileset_file ascon_top3.sv SYSTEM_VERILOG PATH RTL/ASCON_CASE/ascon_top3.sv
add_fileset_file ascon_top4.sv SYSTEM_VERILOG PATH RTL/ASCON_CASE/ascon_top4.sv
add_fileset_file instance_fifo.v VERILOG PATH RTL/ASCON_CASE/instance_fifo.v
add_fileset_file active_ascon.sv SYSTEM_VERILOG PATH RTL/TOP_LEVEL/active_ascon.sv


# 
# parameters
# 
add_parameter ROUNDS_PER_CYCLE0 INTEGER 3
set_parameter_property ROUNDS_PER_CYCLE0 DEFAULT_VALUE 3
set_parameter_property ROUNDS_PER_CYCLE0 DISPLAY_NAME ROUNDS_PER_CYCLE0
set_parameter_property ROUNDS_PER_CYCLE0 TYPE INTEGER
set_parameter_property ROUNDS_PER_CYCLE0 UNITS None
set_parameter_property ROUNDS_PER_CYCLE0 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ROUNDS_PER_CYCLE0 HDL_PARAMETER true
add_parameter ROUNDS_PER_CYCLE1 INTEGER 2
set_parameter_property ROUNDS_PER_CYCLE1 DEFAULT_VALUE 2
set_parameter_property ROUNDS_PER_CYCLE1 DISPLAY_NAME ROUNDS_PER_CYCLE1
set_parameter_property ROUNDS_PER_CYCLE1 TYPE INTEGER
set_parameter_property ROUNDS_PER_CYCLE1 UNITS None
set_parameter_property ROUNDS_PER_CYCLE1 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ROUNDS_PER_CYCLE1 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink iClk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink iRstn reset_n Input 1


# 
# connection point control_slave
# 
add_interface control_slave avalon end
set_interface_property control_slave addressUnits WORDS
set_interface_property control_slave associatedClock clock_sink
set_interface_property control_slave associatedReset reset_sink
set_interface_property control_slave bitsPerSymbol 8
set_interface_property control_slave burstOnBurstBoundariesOnly false
set_interface_property control_slave burstcountUnits WORDS
set_interface_property control_slave explicitAddressSpan 0
set_interface_property control_slave holdTime 0
set_interface_property control_slave linewrapBursts false
set_interface_property control_slave maximumPendingReadTransactions 0
set_interface_property control_slave maximumPendingWriteTransactions 0
set_interface_property control_slave readLatency 0
set_interface_property control_slave readWaitTime 1
set_interface_property control_slave setupTime 0
set_interface_property control_slave timingUnits Cycles
set_interface_property control_slave writeWaitTime 0
set_interface_property control_slave ENABLED true
set_interface_property control_slave EXPORT_OF ""
set_interface_property control_slave PORT_NAME_MAP ""
set_interface_property control_slave CMSIS_SVD_VARIABLES ""
set_interface_property control_slave SVD_ADDRESS_GROUP ""

add_interface_port control_slave iChipSelect_Control chipselect Input 1
add_interface_port control_slave iWrite_Control write Input 1
add_interface_port control_slave iRead_Control read Input 1
add_interface_port control_slave iAddress_Control address Input 2
add_interface_port control_slave iData_Control writedata Input 32
add_interface_port control_slave oData_Control readdata Output 32
set_interface_assignment control_slave embeddedsw.configuration.isFlash 0
set_interface_assignment control_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Master_Read
# 
add_interface Master_Read avalon start
set_interface_property Master_Read addressUnits SYMBOLS
set_interface_property Master_Read associatedClock clock_sink
set_interface_property Master_Read associatedReset reset_sink
set_interface_property Master_Read bitsPerSymbol 8
set_interface_property Master_Read burstOnBurstBoundariesOnly false
set_interface_property Master_Read burstcountUnits WORDS
set_interface_property Master_Read doStreamReads false
set_interface_property Master_Read doStreamWrites false
set_interface_property Master_Read holdTime 0
set_interface_property Master_Read linewrapBursts false
set_interface_property Master_Read maximumPendingReadTransactions 0
set_interface_property Master_Read maximumPendingWriteTransactions 0
set_interface_property Master_Read readLatency 0
set_interface_property Master_Read readWaitTime 1
set_interface_property Master_Read setupTime 0
set_interface_property Master_Read timingUnits Cycles
set_interface_property Master_Read writeWaitTime 0
set_interface_property Master_Read ENABLED true
set_interface_property Master_Read EXPORT_OF ""
set_interface_property Master_Read PORT_NAME_MAP ""
set_interface_property Master_Read CMSIS_SVD_VARIABLES ""
set_interface_property Master_Read SVD_ADDRESS_GROUP ""

add_interface_port Master_Read oAddress_Master_Read address Output 32
add_interface_port Master_Read oRead_Master_Read read Output 1
add_interface_port Master_Read iDataValid_Master_Read readdatavalid Input 1
add_interface_port Master_Read iReadData_Master_Read readdata Input 32
add_interface_port Master_Read iWait_Master_Read waitrequest Input 1


# 
# connection point Master_Write
# 
add_interface Master_Write avalon start
set_interface_property Master_Write addressUnits SYMBOLS
set_interface_property Master_Write associatedClock clock_sink
set_interface_property Master_Write associatedReset reset_sink
set_interface_property Master_Write bitsPerSymbol 8
set_interface_property Master_Write burstOnBurstBoundariesOnly false
set_interface_property Master_Write burstcountUnits WORDS
set_interface_property Master_Write doStreamReads false
set_interface_property Master_Write doStreamWrites false
set_interface_property Master_Write holdTime 0
set_interface_property Master_Write linewrapBursts false
set_interface_property Master_Write maximumPendingReadTransactions 0
set_interface_property Master_Write maximumPendingWriteTransactions 0
set_interface_property Master_Write readLatency 0
set_interface_property Master_Write readWaitTime 1
set_interface_property Master_Write setupTime 0
set_interface_property Master_Write timingUnits Cycles
set_interface_property Master_Write writeWaitTime 0
set_interface_property Master_Write ENABLED true
set_interface_property Master_Write EXPORT_OF ""
set_interface_property Master_Write PORT_NAME_MAP ""
set_interface_property Master_Write CMSIS_SVD_VARIABLES ""
set_interface_property Master_Write SVD_ADDRESS_GROUP ""

add_interface_port Master_Write oAddress_Master_Write address Output 32
add_interface_port Master_Write oData_Master_Write writedata Output 32
add_interface_port Master_Write oWrite_Master_Write write Output 1
add_interface_port Master_Write iWait_Master_Write waitrequest Input 1

